FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app/django_admin

RUN apt-get update \
 && apt-get install -y --no-install-recommends build-essential libpq-dev libjpeg62-turbo-dev zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*

COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ../ /app

RUN python manage.py collectstatic --noinput

EXPOSE 8001

CMD ["/bin/sh", "-c", "python /app/scripts/create_db_and_tables.py && python setup_admin.py && python manage.py runserver 0.0.0.0:8001"]


